# Generated by Django 4.1.4 on 2022-12-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField(verbose_name='Серия')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('release_date', models.DateTimeField(verbose_name='Дата создания')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания активации')),
                ('status', models.BooleanField(verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_use', models.DateTimeField(verbose_name='Дата использования')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardStorage.card', verbose_name='Карта')),
            ],
        ),
    ]
